
DROP TABLE IF EXISTS Data;
DROP TABLE IF EXISTS User;


CREATE TABLE User
(
    Id INTEGER PRIMARY KEY AUTO_INCREMENT,
    User_name VARCHAR(255) NOT NULL ,
    Address_mail VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL
);


CREATE TABLE Data
(
    Id INTEGER PRIMARY KEY AUTO_INCREMENT,
    Encrypted_Uid INTEGER,
    Title VARCHAR(255),
    Identifiant VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Url_site VARCHAR(2083) NOT NULL,
    Notes VARCHAR(1000),
    Expiration_suggestion VARCHAR(10)
);
ALTER TABLE Data ADD CONSTRAINT fk_Uid_User FOREIGN KEY (Encrypted_Uid) REFERENCES User(Id) ON DELETE CASCADE;